### ISSUE TITLE
Error - Pydantic, memory.py

### ISSUE THREAD

**Issue by ebowwa** [alaeddine-13/thinkgpt#3]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from thinkgpt.llm import ThinkGPT
  File "/home/runner/thinkgpt-1/thinkgpt/llm.py", line 14, in <module>
    from thinkgpt.memory import MemoryMixin, ExecuteWithContextChain
  File "/home/runner/thinkgpt-1/thinkgpt/memory.py", line 9, in <module>
    embeddings_model = OpenAIEmbeddings()
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for OpenAIEmbeddings

The error is caused by a pydantic validation error in the OpenAIEmbeddings initialization on line 9 of memory.py. To fix this, you need to check the pydantic documentation to be sure of the correct way to initialize the OpenAIEmbeddings or reach out to the package maintainers.

**Comment by alaeddine-13** [comment]
Hey @ebowwa ,
This is actually an upstream error from langchain. I suggest either tweaking your langchain or pydantic version.
It would be ideal to fix this in langchain
